In [5]:
# make the screen bigger!

from IPython.display import display, HTML

display(HTML(data="""   <style>     div#notebook-container    { width: 100%; }     div#menubar-container     { width: 85%; }     div#maintoolbar-container { width: 99%; } </style>
"""))

# import all our libraries (if this cell throws an error you may need to reinstall a library)
import os
import pandas as pd
import shutil   
import re
from datetime import date, datetime, timedelta
import numpy as np
import matplotlib.pyplot as plt
import scipy
from scipy import stats

%matplotlib notebook

### Import custom functions

In [7]:
from datetime import date, datetime, timedelta

%run Functions/Funcs.py

datapath       = os.path.join('..', 'Raw_data/Weather_stations/Raw_data')
Formatted_data = os.path.join('..', 'Workspace/Formatted_raw_data')

files1 = os.listdir(datapath) # make a list of all the files in the directory
for i in files1: 
    if i.endswith('.xlsx'):
        print(i)
        data_xls = pd.read_excel(os.path.join(datapath, i),  index_col=0)  # read  xlsx to memory
        print(data_xls.head())

In [8]:



        if i.endswith('.xlsx'):
            data_xls = pd.read_excel(os.path.join(datapath, i),  index_col=0)  # read  xlsx to memory
            nam = i.split(".")[0]                                  # remove the .xls
            data_xls.to_csv(os.path.join(datapath2,  nam+'.csv'), encoding='utf-8')       # turn xlsx to csv
            
                       
        if i.endswith(".csv"):
            shutil.copy(os.path.join(datapath, i), datapath2)
    except:  
        print("Problem_with   - {}".format(i))

Problem_with   - Aasu -Weather-0616162.xlsx
Problem_with   - Aasu Downloaded01182016.csv
Problem_with   - Aasu Downloaded01182016.xlsx
Problem_with   - Aasu Wx 020917.csv
Problem_with   - Aasu Wx 020917.xlsx
Problem_with   - Aasu Wx 092816.csv
Problem_with   - Aasu Wx 092816.xlsx
Problem_with   - Aasu Wx 2016 & Notes (2).csv
Problem_with   - Aasu Wx 2016 & Notes (2).xlsx
Problem_with   - Aasu Wx 2016 & Notes (3).csv
Problem_with   - Aasu Wx 2016 & Notes (3).xlsx
Problem_with   - Aasu Wx 2016 & Notes.csv
Problem_with   - Aasu Wx 2016 & Notes.xlsx
Problem_with   - Aasu _Downloaded10072015.csv
Problem_with   - Aasu _Downloaded10072015.xlsx
Problem_with   - Aasu _Wx_071916.csv
Problem_with   - Aasu _Wx_071916.xlsx
Problem_with   - Aasu-Wx-013018.csv
Problem_with   - Aasu-Wx-013018.xlsx
Problem_with   - Afono-Wx-013018.xlsx
Problem_with   - Afono-Wx-102418.xlsx
Problem_with   - Alava -Wx-011818.csv
Problem_with   - Alava Wx 020917.csv
Problem_with   - Alava Wx 020917.xlsx
Problem_with   - Alava Wx 091317.csv
Problem_with   - Alava Wx 091317.xlsx
Problem_with   - Alava Wx 092016.csv
Problem_with   - Alava Wx 092016.xlsx
Problem_with   - Alava Wx 2016 & Notes (2).csv
Problem_with   - Alava Wx 2016 & Notes (2).xlsx
Problem_with   - Alava Wx 2016 & Notes.csv
Problem_with   - Alava Wx 2016 & Notes.xlsx
Problem_with   - Alava Wx Raw1-2017 .csv
Problem_with   - Alava Wx Raw1-2017 .xlsx
Problem_with   - Alava Wx-110217.csv
Problem_with   - Alava Wx-110217.xlsx
Problem_with   - Alava _01042016 (2).xlsx
Problem_with   - Alava _100815.csv
Problem_with   - Alava _100815.xlsx
Problem_with   - Alava-Wx-102418.xlsx
Problem_with   - ASPA_solar  SR Wx 100616.csv
Problem_with   - ASPA_solar  SR Wx 100616.xlsx
Problem_with   - ASPA_solar Solar Rad-0616162.csv
Problem_with   - ASPA_solar Solar Rad-0616162.xlsx
Problem_with   - ASPA_solar Solar Wx 2016 (2).csv
Problem_with   - ASPA_solar Solar Wx 2016 (2).xlsx
Problem_with   - ASPA_solar Solar Wx 2016 (3).csv
Problem_with   - ASPA_solar Solar Wx 2016 (3).xlsx
Problem_with   - ASPA_solar Solar Wx 2016.csv
Problem_with   - ASPA_solar Solar Wx 2016.xlsx
Problem_with   - ASPA_solar SolarRad_071916.csv
Problem_with   - ASPA_solar SolarRad_071916.xlsx
Problem_with   - ASPA_solar Solar_Jan2016.csv
Problem_with   - ASPA_solar Solar_Jan2016.xlsx
Problem_with   - ASPA_solar SR 032817.csv
Problem_with   - ASPA_solar SR 032817.xlsx
Problem_with   - ASPA_solar SR 053117.csv
Problem_with   - ASPA_solar SR 053117.xlsx
Problem_with   - ASPA_solar SR 070917.csv
Problem_with   - ASPA_solar SR 070917.xlsx
Problem_with   - ASPA_solar Wx 091317.csv
Problem_with   - ASPA_solar Wx 091317.xlsx
Problem_with   - ASPA_solar-Wx-110217.csv
Problem_with   - ASPA_solar-Wx-110217.xlsx
Problem_with   - Fagaitua -Wx-011818.csv
Problem_with   - Fagaitua no rain wx 091317.csv
Problem_with   - Fagaitua no rain wx 091317.xlsx
Problem_with   - Fagaitua no rain-Wx-110217.csv
Problem_with   - Fagaitua no rain-Wx-110217.xlsx
Problem_with   - Fagaitua noRain 070917.csv
Problem_with   - Fagaitua noRain 070917.xlsx
Problem_with   - Fagaitua-Wx-102418.xlsx
Problem_with   - Fangaitua Wx station (2).csv
Problem_with   - Fangaitua Wx station (2).xlsx
Problem_with   - Poloa -Wx-011818.csv
Problem_with   - Poloa Wx 020917.csv
Problem_with   - Poloa Wx 020917.xlsx
Problem_with   - Poloa Wx 051917.csv
Problem_with   - Poloa Wx 051917.xlsx
Problem_with   - Poloa Wx 070917.csv
Problem_with   - Poloa Wx 070917.xlsx
Problem_with   - Poloa Wx 091317.csv
Problem_with   - Poloa Wx 091317.xlsx
Problem_with   - Poloa Wx 100316.csv
Problem_with   - Poloa Wx 100316.xlsx
Problem_with   - Poloa Wx 2016 & Notes (2).csv
Problem_with   - Poloa Wx 2016 & Notes (2).xlsx
Problem_with   - Poloa Wx 2016 & Notes (3).csv
Problem_with   - Poloa Wx 2016 & Notes (3).xlsx
Problem_with   - Poloa Wx 2016 & Notes.csv
Problem_with   - Poloa Wx 2016 & Notes.xlsx
Problem_with   - Poloa Wx-110217.csv
Problem_with   - Poloa Wx-110217.xlsx
Problem_with   - Poloa _Downloaded01192016.xlsx
Problem_with   - Poloa _Downloaded10072015.csv
Problem_with   - Poloa _Downloaded10072015.xlsx
Problem_with   - Poloa _Downloaded10072015_jul_oct.csv
Problem_with   - Poloa _Downloaded10072015_jul_oct.xlsx
Problem_with   - Poloa _Wx_071916.csv
Problem_with   - Poloa _Wx_071916.xlsx
Problem_with   - Poloa-Wx-102418.xlsx
Problem_with   - Vaipito -Weather-June061616.csv
Problem_with   - Vaipito -Weather-June061616.xlsx
Problem_with   - Vaipito -Weather-May.csv
Problem_with   - Vaipito -Weather-May.xlsx
Problem_with   - Vaipito Wx_071916.csv
Problem_with   - Vaipito Wx_071916.xlsx
Problem_with   - Vaipito _Wx09292015.csv
Problem_with   - Vaipito _Wx09292015.xlsx
Problem_with   - Vaipito _Wx201507.csv
Problem_with   - Vaipito _Wx201507.xlsx
Problem_with   - Vaipito _Wx20150722.csv
Problem_with   - Vaipito _Wx20150722.xlsx
Problem_with   - Vaipito _Wx20160119.csv
Problem_with   - Vaipito _Wx20160119.xlsx
Problem_with   - Vaipito _WxSD201508.csv
Problem_with   - Vaipito _WxSD201508.xlsx
Problem_with   - Vaipito _WxSD201509.csv
Problem_with   - Vaipito _WxSD201509.xlsx
Problem_with   - Vaipito-Weather-June0616161.csv
Problem_with   - Vaipito-Weather-June0616162.csv
Problem_with   - Vaipito-Weather-May2.csv
Problem_with   - Vaipito_Wx.09292015.csv
Problem_with   - Vaipito_Wx.201507.csv
Problem_with   - Vaipito_Wx.20150722.csv
Problem_with   - Vaipito_Wx.20160119.csv
Problem_with   - Vaipito_Wx.SD201508.csv
Problem_with   - Vaipito_Wx.SD201509.csv
Problem_with   - Vaipito_Wx_09292015.csv
Problem_with   - Vaipito_Wx_201507.csv
Problem_with   - Vaipito_Wx_20150722.csv
Problem_with   - Vaipito_Wx_20160119.csv
Problem_with   - Vaipito_Wx_SD201508.csv
Problem_with   - Vaipito_Wx_SD201509.csv
Problem_with   - Vipito_Wx_071916.csv
Problem_with   - Vipito_Wx_071916.xlsx

In [98]:
def xls_cleaner(file_2_read, datetime_name = ["Date and Time", "Timestamp",  "TIMESTAMP"] ):

    data_xls = pd.read_excel(file_2_read,  header=None, index_col=None)  # read  xlsx to memory
    data_xls_trimmed = data_xls.apply(lambda x: x.str.strip() if x.dtype == "object" else x)
    Col_true = data_xls_trimmed[data_xls_trimmed.isin(datetime_name)]
    Col_true = Col_true.dropna(how='all')
    finally_frame = Col_true.dropna(axis = 1, how='all')
    rows_to_skip = finally_frame.index[0]
    index_col_number = finally_frame.columns[0]

    data = pd.read_excel(os.path.join(datapath, files1[3]),  skiprows=rows_to_skip,  index_col=index_col_number)  # read  xlsx to memory

    return data

In [104]:
xls_cleaner(os.path.join(datapath, files1[3]))

,TMPA,TMPB,TMPC,TMPD,TMPE,SRD,HMD,TMP,RNF,WND,WNG,WNS,DEW
Date and Time,,,,,,,,,,,,,
2015-07-21 13:15:00,NaN,NaN,NaN,NaN,NaN,385,65.9,78.0,0.03,255,13,7,65.9
2015-07-21 13:30:00,NaN,NaN,NaN,NaN,NaN,489,74.4,76.0,0.02,169,15,7,67.4
2015-07-21 13:45:00,NaN,NaN,NaN,NaN,NaN,538,75.6,75.2,0.00,139,14,7,67.1
2015-07-21 14:00:00,NaN,NaN,NaN,NaN,NaN,766,73.6,76.0,0.00,139,13,6,67.1
2015-07-21 14:15:00,NaN,NaN,NaN,NaN,NaN,611,73.6,75.9,0.00,142,17,8,67.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2016-01-19 12:45:00,NaN,NaN,NaN,NaN,NaN,842,78.2,81.2,0.00,173,11,2,73.9
2016-01-19 13:00:00,NaN,NaN,NaN,NaN,NaN,299,79.4,80.4,0.00,186,9,2,73.6
2016-01-19 13:15:00,NaN,NaN,NaN,NaN,NaN,433,79.2,80.1,0.00,193,14,3,73.2
2016-01-19 13:30:00,NaN,NaN,NaN,NaN,NaN,496,79.2,80.2,0.00,208,15,3,73.3
2016-01-19 13:45:00,NaN,NaN,NaN,NaN,NaN,474,80.4,79.9,0.00,228,15,4,73.4

In [102]:
files1[3]

'Aasu Downloaded01182016.xlsx'

In [91]:
finally_frame.columns[0]

0

In [84]:
fuckinga

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Date and Time,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15117,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15118,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15119,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15120,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15121,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN